### PR TITLE
Make scratch dir writable before attempting removal.

### PR DESCRIPTION
**Pull request by jakewendt**

### CODE REVIEW

**Comment by HenrikBengtsson** [comment]
Thxs. So the reason for that `cd /scratch` that you dropped is that I don't know if it is safe (=unknown if it cause problems) to delete the folder that is also the current working directory. Would you mind adding that back just in case?

**Comment by jakewendt** [comment]
Done

**Comment by HenrikBengtsson** [comment]
Thanks. Now live :)

**Comment by jakewendt** [comment]
anytime

**Pull request merged**
